name: Deploy to wordpress.org

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to wordpress.org SVN
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.WPORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WPORG_PASSWORD }}
          SLUG: dislike404-broken-link-checker
          ASSETS_DIR: .wordpress-org